"""Add so_tien column to NguoiDung

Revision ID: e9254f8584a4
Revises: 
Create Date: 2025-04-09 14:59:34.043815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9254f8584a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nguoi_dung', schema=None) as batch_op:
        batch_op.drop_index('tk')

    op.drop_table('nguoi_dung')
    op.drop_table('danh_muc_cp')
    op.drop_table('lich_su_gd')
    with op.batch_alter_table('linh_vuc', schema=None) as batch_op:
        batch_op.drop_index('ten_linh_vuc')

    op.drop_table('linh_vuc')
    op.drop_table('loai_cp')
    op.drop_table('tong_gia_tri_trong_ngay')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tong_gia_tri_trong_ngay',
    sa.Column('id_nguoi_dung', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', sa.DATE(), nullable=False),
    sa.Column('gia_tri_tong_tai_san', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['id_nguoi_dung'], ['nguoi_dung.id'], name='tong_gia_tri_trong_ngay_ibfk_1'),
    sa.PrimaryKeyConstraint('id_nguoi_dung', 'time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('loai_cp',
    sa.Column('ma_cp', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('ten_linh_vuc', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['ten_linh_vuc'], ['linh_vuc.ten_linh_vuc'], name='loai_cp_ibfk_1'),
    sa.PrimaryKeyConstraint('ma_cp'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('linh_vuc',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ten_linh_vuc', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('linh_vuc', schema=None) as batch_op:
        batch_op.create_index('ten_linh_vuc', ['ten_linh_vuc'], unique=True)

    op.create_table('lich_su_gd',
    sa.Column('id_gd', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_nguoi_dung', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', mysql.DATETIME(), nullable=False),
    sa.Column('ma_cp', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('so_luong', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gia_tri', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['id_nguoi_dung'], ['nguoi_dung.id'], name='lich_su_gd_ibfk_1'),
    sa.PrimaryKeyConstraint('id_gd'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('danh_muc_cp',
    sa.Column('id_nguoi_dung', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ma_cp', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('so_luong', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_nguoi_dung'], ['nguoi_dung.id'], name='danh_muc_cp_ibfk_1'),
    sa.PrimaryKeyConstraint('id_nguoi_dung', 'ma_cp'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('nguoi_dung',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ten', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('tk', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('mk', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('nguoi_dung', schema=None) as batch_op:
        batch_op.create_index('tk', ['tk'], unique=True)

    # ### end Alembic commands ###
